### ISSUE TITLE
REPL mode interaction between VS Code and Hammerspoon Console

### ISSUE THREAD

**Issue by velios** [sisoe24/hammerspoon-vscode#3]
Hello. First of all thank you for amazing job.

Is it possible to prototype with hammerspoon-vscode extension in REPL mode. Like we do it in Hammerspoon Console or Python REPL for example. Just send commands to execute and get request back, but with convenience and autosuggestions of your plugin. If hammerspooon config is big not cool to always reload whole config to test small prototype.

**Comment by sisoe24** [comment]
Hey, thanks for reaching out!

You're right! It should be possible to execute a chunk of code, or even an entire file, without reloading Hammerspoon itself. We could use the `hs.ipc` module to pass the selected text to Hammerspoon for execution. I'm already using this method for sending some commands to Hammerspoon myself

https://github.com/sisoe24/hammerspoon-vscode/blob/cc05b3d4e87cee97d66fcd11ccb2943487854350/src/hammerspoon.ts#L290

The main task should be exposing this feature to the user, including choosing to execute the selected text or the entire document. The only issue I foresee is that Lua allows single and double-quoted strings. Because we would send the command inside a string `hs -c "${code}"`, it will break the code in cases like `hs -c "print("hello")"`. 

If you're interested in tackling this, I would happily guide you through the process. Just let me know!

**Comment by velios** [comment]
I definitely interested in it. It seems like a killer feature for fast hammerspoon prototyping for me. If I clearly understand we can escape strings in lua also with `[[<string>]]` syntax. I'm not sure, but maybe it can solve caveat mentioned by you. Like this `utils.execSync("hs -c [[${code}]]");` I found it [here](https://www.tutorialspoint.com/lua/lua_strings.htm) and test in hammerspoon console. I'm not written extension for vs-code before, but i have some experience in coding. I'll wait for you guidance.

**Comment by sisoe24** [comment]
Ok, give me some time because I want to clean up some old code, and re-enable the test. Once done I will tell you how to start. It's going to be very easy and fun. 

For now, you can try to find a solution for the problem I mentioned by making another script. Just keep in mind that using the Lua multiline string syntax won't work in this case because it will be interpreted by the terminal, like Bash/Zsh.

I made you example script where you can experiment

```js
import * as cp from "child_process";

const luaScript = `
local foo = 'hello'
hs.alert.show(foo)
`

// not working because world is double quoted: the same quotes we use in the `cmd` var
const notWorking = `
local foo = 'hello'
local bar = "world"
hs.alert.show(foo .. ' ' .. bar)
`

// the script needs to be wrapped in some quotes, otherwise it will break.
// but it will also break if it encounters the same quotes inside the script.
const cmd = `hs -c "${luaScript}"`
const result = cp.execSync(cmd, { encoding: "utf-8" });
console.log(result);
```

To run this code on your machine, you need to have [Node.js](https://nodejs.org/en) and Hammerspoon [hs.ipc](https://www.hammerspoon.org/docs/hs.ipc.html) installed.

**Comment by velios** [comment]
Thanks for this example. I tried simple solution and it works for me in Node REPL. Can we use it?

```javascript
import * as cp from "child_process";

const notWorking = `
local foo = 'hello'
local bar = "world"
hs.alert.show(foo .. ' ' .. bar)
`

function escapeDoubleQuotes(s) {
  return s.replace(/["]/g, '\\$&');
}

const working = escapeDoubleQuotes(notWorking)
const cmd = `hs -c "${working}"`
const res = cp.execSync(cmd, { encoding: "utf-8" });
console.log(res);
```

**Comment by sisoe24** [comment]
This would work nicely, but I believe this would break when there are escaped double quotes: 

- `"Hello from \"Lua\""`
- `string.find(str, "\"[^\"]*\"")`

Changes are slim that someone writes double-quoted strings with escaped double quotes, but you never know 😅

**Comment by velios** [comment]
Fair point, we never know what user do. Maybe we can use this approach?

```javascript
import * as cp from "child_process";

// Some trouble in next block. In Lua we use \" to escape, but javascript use \\" syntax.
// We need two step transformation here.
// First when we grab user input from vscode translate \" escaped chars to \\" variant.
// If we do that than solution will work.
notWorking = `
local foo = 'hello'
local bar = "from \\"Lua\\"" 
hs.alert.show(foo .. ' ' .. bar)
`

function escapeString(str) {
  return str.replace(/["[\]\\]/g, '\\$&');
}

working = escapeString(notWorking)
cmd = `hs -c "${working}"`
res = cp.execSync(cmd, { encoding: "utf-8" });
```

**Comment by sisoe24** [comment]
@velios If you need any help or have any concerns, feel free to ask me. I will try out the code snippet either today or tomorrow.

# How to contribute

## Fork the project

Fork the project and branch out from the `develop` branch. Create a new branch with the name of the feature you are working on and start working on it.

## Node.js

This project uses Node.js. You can download it from [here](https://nodejs.org/en/download/). Once installed, you can run the following command to install all the dependencies:

```bash
cd vscode-hammerspoon
npm install
```

## Run the project

The project offers two ways to run in development mode: 

- The `Run Extension` command will run the extension in a new VSCode window
- The `Run Tests` command will run the extension in a new VSCode window and run the tests.

For now we will use the `Run Extension` command. To run the extension, press `F5` or go to the `Run` menu and click on `Start Debugging`. This will open a new VSCode window with the extension running.

Once the extension is running, you can open the command palette and type any of the commands that the extension offers. In our case, can start typing Hammerspoon and you will see the commands that the extension offers.

## Add a new command

To add a new command, you need to add a new entry to the `package.json` file. The entry should look like this:

```json
"contributes": {
    "commands": [
        {
            "command": "hammerspoon.executeSelectedText",
            "title": "Execute selected text"
        }
    ],
    // You can also add the command to a menu
    "menus": {
        "editor/context": [
            {
                "command": "hammerspoon.executeSelectedText",
                "group": "navigation",
                "when": "editorTextFocus"
            }
        ]
    }

}
```

> You can find more information about the `package.json` file [here](https://code.visualstudio.com/api/references/contribution-points#contributes.commands).

Once you have added the entry, you need to add the function that will be called when the command is executed. To do this, open the `extension.ts` file and add the following code:

```ts
// extensions.ts
  context.subscriptions.push(
        // Register the command you added to the package.json file
        vscode.commands.registerCommand("hammerspoon.executeSelectedText", () => {
            // Your code here
        })
    );
```


## Code examples

The extension uses TypeScript and the VSCode API. You can find more information about the API [here](https://code.visualstudio.com/api/references/vscode-api).

I believe that the best way to learn is by doing so I will leave you with some hints and you can try to implement the commands yourself. If you get stuck you can always check the code in the repository since there are many similar examples.



```ts
// your file.ts

import * as vscode from "vscode";
import { runSync } from "./run_cmd";
import { outputWindow } from "./console";

/**
 * Get the selected text
 * @returns The selected text
 */
function getSelectedText(): string | null {
    // Get the current editor
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
        return null;
    }

    ...

    return // get the editor document selected text
}


/**
 * Execute the selected text
 * @param command The command to execute
 * @returns The output of the command
 */
function executeCode(command: string): string | null {
    // run the command in the shell and get the output
    ...

    // Show the output in the output window
    // or in a vscode notification panel?
    ...

    return output;
}

const selectedText = getSelectedText();
if (selectedText) {
    executeCode(selectedText);
}
```

## TODOs

- [ ] Add a new command to execute the selected text
- [ ] Add a new command to execute the current file
- [ ] Add a new command to execute the current line

**Comment by velios** [comment]
@sisoe24, thank you for teaching how to fish, and not giving ready-made fish. Your instruction is something amazing, because in an hour in the evening I was able to make a PR in which the functionality works, though so far only with selected text. And thanks again for taking the time to teach, it is very valuable, I am grateful to you. Also i check and lua script code executes with tricky cases, which we discuss above. 

P.S. Unfortunately, my code could not pass all the necessary checks, which I received a notification about. But I haven't figured out what's going on yet.

**Comment by velios** [comment]
@sisoe24 Can you explain how i can compile and use version of extension from local codebase, against already download version in extension tab of vscode? I want to try it and test how comfortable to use REPL functionality in my actual vscode editor, not in demo version.

**Comment by velios** [comment]
Add PR https://github.com/sisoe24/hammerspoon-vscode/pull/4 Don't know how to bond it to issue

**Comment by sisoe24** [comment]
> @sisoe24 Can you explain how i can compile and use version of extension from local codebase, against already download version in extension tab of vscode? I want to try it and test how comfortable to use REPL functionality in my actual vscode editor, not in demo version.

you can compile the extension with `vsce package`. `vsce` is an npm package you can download from with `npm install --global vsce`. [https://www.npmjs.com/package/vsce](url).

**Comment by velios** [comment]
Yahoo! Thank you for helping me fulfill my request. You were very patient in teaching me.

**Comment by sisoe24** [comment]
Hey @velios, it was a pleasure! I'm always happy to help.

I have one final request to ask of you. I just made a significant change to how the suggestions are generated, and I would like you to try it before we merge it into the main release.

You'll need to pull from the `develop` branch and try the extension to do so. You should receive a notification about the new update, but if not, you can manually download and install the `Hammerspoon: Add Stubs` command. This will install some stubs in your `.hammerspoon` directory. The stubs require the [Lua LSP](https://marketplace.visualstudio.com/items?itemName=sumneko.lua) server to be installed, but it should be automatically downloaded from the next update.

Once everything is set up, you should see a folder called `~/.hammerspoon/Spoons/EmmyLua.spoon/annotations`, as well as a setting pointing to that path in your Preferences `Lua.workspace.library`. From there, you should be able to use the new suggestions and may want to disable the old ones in the settings using the `Hammerspoon: Enable Legacy Provider` command.

I also updated the README with the new information.

If there is a problem in the setup we might want to start a new issue.

**Comment by sisoe24** [comment]
@velios To use the Lua LSP, extensions must be enabled so you need to comment out/remove the `--disable-extensions` field in `.vscode/launch.json` which will enable your environment extensions.

**Comment by velios** [comment]
@sisoe24 All works fine. EmmyLua installed, Lua.workspace.library option appeared, i see underlined hints, etc. But i don't really understand how to test well difference between old and new approaches.

Also `hammerspoon.useLegacyProviders` setting and `Hammerspoon: Enable Legacy Provider` menu item not developed yet if I understand correct. I don't see it in code of develop branch.

**Comment by sisoe24** [comment]
Yes, thanks for pointing that out. The settings name was not updated (now is `hammerspoon.enableLegacyProviders`). Also, the fact that you could run and see the underlined hints is good enough as a test.
